version: '3.8'
services:
  # PHP/Apache service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customeTrack_app
    ports:
      - '8080:80' # Map port 80 in the container to 8080 on the host
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # MySQL service
  db:
    image: mysql:5.7
    container_name: customeTrack_db
    environment:
      MYSQL_DATABASE: customeTrack_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
