# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html
#     ports:
#       - "8000:9000"
#     networks:
#       - laravel
#     environment:
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=customer_track_database
#       - DB_USERNAME=customer_track_username
#       - DB_PASSWORD=customer_track_password
#       - APP_ENV=local
#       - APP_DEBUG=true
#     depends_on:
#       db:
#         condition: service_healthy
#     command: ["sh", "-c", "php artisan migrate --force"]

#   db:
#     image: mysql:8.0
#     container_name: laravel_db
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: customer_track_database
#       MYSQL_USER: customer_track_username
#       MYSQL_PASSWORD: customer_track_password
#     volumes:
#       - dbdata:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     networks:
#       - laravel

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     restart: unless-stopped
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "8080:80"
#     networks:
#       - laravel

# networks:
#   laravel:

# volumes:
#   dbdata:

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    networks:
      - laravel
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=custome_track
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=9000"]

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: custome_track
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p=root"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
